# Generated by Django 4.2.1 on 2023-05-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_coverage', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='non_coverage',
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='non_coverage',
        ),
        migrations.DeleteModel(
            name='Non_coverage',
        ),
        migrations.AddField(
            model_name='doctor',
            name='coverage_item',
            field=models.ManyToManyField(to='diagnosis.coverageitem'),
        ),
    ]
