# Generated by Django 4.2.1 on 2023-05-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0003_openinghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='coverage_item',
            field=models.ManyToManyField(blank=True, to='diagnosis.coverageitem'),
        ),
    ]
