# Generated by Django 4.2.1 on 2023-05-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0004_alter_doctor_coverage_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghours',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('mon', '월요일'), ('tue', '화요일'), ('wed', '수요일'), ('thu', '목요일'), ('fri', '금요일'), ('sat', '토요일'), ('sun', '일요일')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
