# Generated by Django 4.2.1 on 2023-05-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0006_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
