# Generated by Django 4.2.1 on 2023-05-24 05:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0007_diagnosis_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='expiration_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
