# Generated by Django 4.2.1 on 2023-05-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0008_diagnosis_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='expiration_time',
            field=models.DateTimeField(null=True),
        ),
    ]
