# Generated by Django 4.2.1 on 2023-05-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0010_alter_hospital_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
